FORMAT: 1A
HOST: https://examin-app.herokuapp.com/api

# Examin WebAPIドキュメント

# Group Overview
## Examin WebAPI について
<!-- include(overview/index.apib) -->
## API共通のエラー形式
<!-- include(overview/errors.apib) -->
## モデルの補足
<!-- include(overview/models.apib) -->

# Group 認証用 API
<!-- include(api/auth.apib) -->
# Group 共通 API
<!-- include(api/users.apib) -->

# Group Teachers / Problems API
<!-- include(api/teachers/problems.apib) -->
# Group Teachers / ProblemsUsers API
<!-- include(api/teachers/problems_users.apib) -->
# Group Teachers / Questions API
<!-- include(api/teachers/questions.apib) -->
# Group Teachers / Students API
<!-- include(api/teachers/students.apib) -->
# Group Teachers / Teachers API
<!-- include(api/teachers/teachers.apib) -->

# Group Students / Problems API
<!-- include(api/students/problems.apib) -->
# Group Students / ProblemsUsers API
<!-- include(api/students/problems_users.apib) -->
# Group Students / Questions API
<!-- include(api/students/questions.apib) -->

# Data Structure
<!-- include(data/errors.apib) -->

<!-- include(data/models/achievement.apib) -->
<!-- include(data/models/answer.apib) -->
<!-- include(data/models/problem.apib) -->
<!-- include(data/models/problems_user.apib) -->
<!-- include(data/models/question.apib) -->
<!-- include(data/models/user.apib) -->
