swagger: '2.0'
info:
  description: examin API 設計
  version: 0.0.1
  title: examin
schemes:
  - https
host: examin-api.herokuapp.com
basePath: /api
produces:
  - application/json
paths:
  /auth:
    post:
      tags:
        - 認証用API
      summary: ログイン認証用API
      parameters:
        - in: body
          name: auth
          schema:
            type: object
            properties:
              login_id:
                type: string
              password:
                type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Auth'
        '401':
          $ref: '#/responses/UnAuthorized'
    get:
      tags:
        - 認証用API
      summary: 認証情報取得API
      parameters:
        - $ref: '#/parameters/AuthorizationParam'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Auth'
        '401':
          $ref: '#/responses/UnAuthorized'
  /users/check_unique:
    post:
      tags:
        - Users API
      summary: ユニーク制約用API
      parameters:
        - $ref: '#/parameters/AuthorizationParam'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CheckUnique'
        '400':
          $ref: '#/responses/BadRequest'
  /students/problems:
    get:
      tags:
        - Students / Problems API
      summary: 問題集一覧取得API
      parameters:
        - $ref: '#/parameters/AuthorizationParam'
      responses:
        '200':
          description: OK
          schema:
            properties:
              problems:
                $ref: '#/definitions/Problems'
        '401':
          $ref: '#/responses/UnAuthorized'
  /teachers/problems:
    get:
      tags:
        - Teachers / Problems API
      summary: 問題集一覧取得API
      parameters:
        - $ref: '#/parameters/AuthorizationParam'
      responses:
        '200':
          description: OK
          schema:
            properties:
              problems:
                $ref: '#/definitions/Problems'
        '401':
          $ref: '#/responses/UnAuthorized'
  /teachers/students:
    post:
      tags:
        - Teachers / Students API
      summary: 生徒登録API
      parameters:
        - $ref: '#/parameters/AuthorizationParam'
        - name: student
          in: body
          schema:
            properties:
              teacher:
                $ref: '#/definitions/UserCreate'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/UnAuthorized'
  /teachers/teachers:
    post:
      tags:
        - Teachers / Teachers API
      summary: 講師登録API
      parameters:
        - $ref: '#/parameters/AuthorizationParam'
        - name: teacher
          in: body
          schema:
            properties:
              teacher:
                $ref: '#/definitions/UserCreate'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/UnAuthorized'
        
parameters:
  AuthorizationParam:
    in: header
    name: Authorization
    description: 実行時に返ってくる値 or Cookie に入っている値
    type: string
    required: true

responses:
  BadRequest:
    description: リクエスト情報が正しくない．
    schema:
      $ref: '#/definitions/Error'
  UnAuthorized:
    description: 未ログイン．
    schema:
      $ref: '#/definitions/Error'
  Forbidden:
    description: 権限がない．
    schema:
      $ref: '#/definitions/Error'
  NotFound:
    description: ページが見つからない．
    schema:
      $ref: '#/definitions/Error'
  ServerError:
    description: サーバーエラー．
    schema:
      $ref: '#/definitions/Error'

definitions:
  Auth:
    type: object
    properties:
      access_token:
        type: string
      exprired_at:
        type: string
        format: date-time
      user:
        type: object
        properties:
          id:
            type: integer
          role:
            type: integer
  CheckUnique:
    type: object
    properties:
      check_unique:
        type: boolean
        example: true
  Error:
    type: object
    properties:
      status:
        type: integer
      description:
        type: string
  Problem:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      content:
        type: string
      teacher_name:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
  Problems:
    type: array
    items:
      $ref: '#/definitions/Problem'
  User:
    type: object
    properties:
      login_id:
        type: string
      name:
        type: string
      school:
        type: string
  UserCreate:
    type: object
    properties:
      login_id:
        type: string
      name:
        type: string
      school:
        type: string
      password:
        type: string
      password_confirmation:
        type: string
  Achievement:
    type: object
    properties:
      id:
        type: integer
      problems_user_id:
        type: integer
      question_id:
        type: integer
      result:
        type: boolean
      user_choice:
        type: integer
      answer_time:
        type: integer
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
  Achievements:
    type: array
    items:
      $ref: '#/definitions/Achievement'

