## Achievement [/teachers/achievements]
### 成績一覧取得API [GET]
+ Response 200 (application/json)

## Achievement [/teachers/problems/{problem_id}/achievements]
### 成績一覧(問題)取得API [GET]
+ Response 200 (application/json)

## Achievement [/teachers/students/{student_id}/achievements]
### 成績一覧(生徒)取得API [GET]
+ Response 200 (application/json)

## Achievement [/teachers/achievements/{id}]
### 成績詳細取得API [GET]
+ Response 200 (application/json)

