## ProblemsUser [/teachers/problems_users]
### 成績一覧取得API [GET]
+ Response 200 (application/json)

## ProblemsUser [/teachers/problems_users/problems/{id}]
### 成績一覧(問題)取得API [GET]
+ Response 200 (application/json)

## ProblemsUser [/teachers/problems_users/students/{id}]
### 成績一覧(生徒)取得API [GET]
+ Response 200 (application/json)

## ProblemsUser [/teachers/problems_users/{id}]
### 成績詳細取得API [GET]
+ Response 200 (application/json)

