## ProblemsUser [/students/problems_users]
### 成績一覧取得API [GET]
+ Request (application/json)

	+ Headers

			access-token: 認証用のアクセストークン

+ Response 200 (application/json)
	+ Attributes (ProblemsUsers)

+ Response 401 (application/json)
	+ Attributes (ErrorUnauthorized)

+ Response 422 (application/json)
	+ Attributes (ErrorRecordInvalid)

## ProblemsUser [/students/problems_users/{id}]
### 成績詳細取得API [GET]
+ Request (application/json)

	+ Headers

			access-token: 認証用のアクセストークン

+ Parameters
	+ id: 1 (number)

+ Response 200 (application/json)
	+ Attributes
		+ problemsUser (ProblemsUser)
		+ achievements (Achievements)

+ Response 401 (application/json)
	+ Attributes (ErrorUnauthorized)

