## Question [/teachers/problems/{problem_id}/questions]
### 問題一覧取得API [GET]
+ Request (application/json)

	+ Headers

			access-token: 認証用のアクセストークン

+ Parameters
	+ problem_id: 1 (number)

+ Response 200 (application/json)
	+ Attributes (Questions)

+ Response 401 (application/json)
	+ Attributes (ErrorUnauthorized)

### 問題作成API [POST]
+ Request (application/json)

	+ Headers

			access-token: 認証用のアクセストークン

	+ Attributes (QuestionForm)

+ Parameters
	+ problem_id: 1 (number)

+ Response 200 (application/json)
	+ Attributes (Questions)

+ Response 401 (application/json)
	+ Attributes (ErrorUnauthorized)

+ Response 422 (application/json)
	+ Attributes (ErrorRecordInvalid)

## Question [/teachers/problems/{problem_id}/questions/{id}/edit]
### 問題編集取得API [GET]
+ Request (application/json)

	+ Headers

			access-token: 認証用のアクセストークン

+ Parameters
	+ id: 1 (number)
	+ problem_id: 1 (number)

+ Response 200 (application/json)
	+ Attributes (Questions)

+ Response 401 (application/json)
	+ Attributes (ErrorUnauthorized)

## Question [/teachers/problems/{problem_id}/questions/{id}]
### 問題詳細取得API [GET]
+ Request (application/json)

	+ Headers

			access-token: 認証用のアクセストークン

+ Parameters
	+ id: 1 (number)
	+ problem_id: 1 (number)

+ Response 200 (application/json)
	+ Attributes (Questions)

+ Response 401 (application/json)
	+ Attributes (ErrorUnauthorized)

### 問題編集API [PUT]
+ Request (application/json)

	+ Headers

			access-token: 認証用のアクセストークン

	+ Attributes (QuestionForm)

+ Parameters
	+ id: 1 (number)
	+ problem_id: 1 (number)

+ Response 200 (application/json)
	+ Attributes (Questions)

+ Response 401 (application/json)
	+ Attributes (ErrorUnauthorized)

+ Response 422 (application/json)
	+ Attributes (ErrorRecordInvalid)

