## Question [/students/problems/{problem_id}/questions]
### 問題一覧取得API [GET]
+ Request (application/json)

	+ Headers

			access-token: 認証用のアクセストークン

+ Parameters
	+ problem_id: 1 (number)

+ Response 200 (application/json)
	+ Attributes (Questions)

+ Response 401 (application/json)
	+ Attributes (ErrorUnauthorized)

## Question [/students/problems/{problem_id}/questions/random]
### 問題一覧(ランダム)取得API [GET]

ここに表示する Request, Response は，問題形式が文字列入力の場合のものである．     
問題形式が択一選択の場合，Response の形が以下のように変わる

```
[
	{
		"sentence": "問題文1",
		"type": 1,
		"correct": 1, - 正解の番号
		"answers": ["解答1", "解答2", "解答3", "解答4"] - 選択肢
	},
	{
		"sentence": "問題文1",
		"type": 1,
		"correct": "解答"
		"correct": 1, - 正解の番号
		"answers": ["解答1", "解答2", "解答3", "解答4"] - 選択肢
	}
]
```

+ Request (applicaiton/json)

	+ Headers

			access-token: 認証用のアクセストークン

	+ Attributes
		+ count: 1 (number) - 取得問題数

+ Parameters
	+ problem_id: 1 (number)

+ Response 200 (application/json)
	+ Attributes (Questions)

+ Response 401 (application/json)
	+ Attributes (ErrorUnauthorized)

+ Response 422 (application/json)
	+ Attributes (ErrorRecordInvalid)

