* Achievement

```
achievement モデルの user_choice カラムに関して     

* -1　　: 未解答で時間切れ
* -1以外: 解答した値が入る
```

```
achievement モデルの answer_time カラムに関して     

-> 生徒が解答するまでにかかった時間が入る
```

* Question

```
question モデルの type カラムに関して     

* 1: 択一形式(どれか一つを選んでもらう形式)
* 2: 複数回答(いくつかの回答を選んでもらう形式)
* 3: 文字列入力(回答を文字で入力してもらう形式)
```

